version: '2'

services:
  redis:
    image: redis:alpine
    container_name: redis_db
    ports:
      - 6379:6379

  redisinsight:
    depends_on:
      - redis
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - 8001:8001
    links:
      - redis:redis